sudo: required
services:
    - docker

before_install:
    - git clone https://github.com/JanneVirkkunen/multi-client.git ./client
    - docker build -t ydog/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ydog/react-test npm test -- --watchAll=false

after_success:
    - docker build -t ydog/multi-client ./client
    - docker build -t ydog/multi-nginx ./nginx
    - docker build -t ydog/multi-server ./server
    - docker build -t ydog/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push ydog/multi-client
    - docker push ydog/multi-nginx
    - docker push ydog/multi-server
    - docker push ydog/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-north-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-north-1-943779574446
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

#deploy:
#    edge: true
#    provider: elasticbeanstalk